version: '3'
services:
  hackathon_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon_api
    ports:
      - "8000:8000"
    volumes: 
      - .:/usr/src/app
    command: >
      sh -c  "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"