# Generated by Django 2.1.7 on 2019-03-29 17:46

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fullName', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('telephoneExtension', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('parentId', models.IntegerField(blank=True, default=-1, null=True)),
                ('topParentId', models.IntegerField(blank=True, default=-1, null=True)),
                ('ancestorIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1, null=True), size=None)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('keywords', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
